[package]
name = "axum-oidc"
description = "A OpenID Connect Client and Bearer Token Libary for axum"
version = "0.0.0"
edition = "2021"
authors = [ "Paul Z <info@pfz4.de>" ]
readme = "README.md"
repository = "https://github.com/pfz4/axum-oidc"
license = "LGPL-3.0-or-later"
keywords = [ "axum", "oidc", "openidconnect", "authentication" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
